name: QTS Query Every 59 Minutes

on:
  schedule:
    - cron: '*/59 * * * *'
  workflow_dispatch:

jobs:
  call-api-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase GET Function 'gradespark'
        run: |
          curl -f -L -X GET 'https://qzwfyjuathzorckzthcy.supabase.co/functions/v1/gradespark' \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"